---
title: "Final_Project"
author: "Sylvia Brown, Pierina Forastieri, Julia Buschmann, Marlyn Bruno"
date: "2022-04-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
```

``` {r add-libraries}
library(tidyverse)
library(ipumsr)
library(srvyr)
library(haven)
library(formattable)
library(ggalt)
library(labelled)
library(sjlabelled)
```


```{r loading data}
ddi <- read_ipums_ddi("data/cps_00004.xml")
data <- read_ipums_micro(ddi) %>%
  janitor::clean_names()

cps_svy <- data %>%
  filter(empstat != 1) %>% #filter out people in armed forces
  filter(age >= 18 & age < 66) %>% #filter out minors; leave only adults
  mutate(employed = case_when(
    empstat == 10 | empstat == 12 ~ 1,
    empstat == 21 | empstat == 22 ~ 0,
    TRUE ~ NA_real_
  )) %>%
  mutate_at(vars(offpov, himcarenw, caidnw, anycovly, prvtcovnw, grpcovnw, mrkcovnw, mrkscovnw, mrkucovnw, inhcovnw, sex), list(~ case_when(
    . == 2 ~ 1,
    . == 1 ~ 0,
    TRUE ~ NA_real_
  ))) %>%
  mutate(unitsstr = case_when(
    unitsstr == 00 ~ NA_real_,
    TRUE ~ as.numeric(unitsstr)
  )) %>%
  mutate(region = case_when(
    region == 97 ~ NA_real_,
    TRUE ~ as.numeric(region)
  )) %>%
  filter(statefip <= 56) %>% # drop weird multi-state fips codes
  mutate(metro = case_when(
    metro == 0 | metro >= 4 ~ NA_real_,
    TRUE ~ as.numeric(metro)
  )) %>%
  mutate(metarea = case_when(
    metarea >= 9997 ~ NA_real_,
    TRUE ~ as.numeric(metarea)
  )) %>%
  mutate(metfips = case_when(
    metfips >= 99998 ~ NA_real_,
    TRUE ~ as.numeric(metfips)
  )) %>%
  mutate(hhincome = case_when(
    hhincome == 9999999 ~ NA_real_,
    TRUE ~ as.numeric(hhincome)
  )) %>%
  mutate_at(vars(county, empstat, labforce, disabwrk), list(~ case_when(
    . == 0 ~ NA_real_,
    TRUE ~ as.numeric(.)
  ))) %>%
    mutate(educ = case_when(
    educ == 001 | educ == 999 ~ NA_real_,
    TRUE ~ as.numeric(educ)
  )) %>%
  mutate(ftotval = case_when(
    ftotval == 9999999999 ~ NA_real_,
    TRUE ~ as.numeric(ftotval)
  )) %>%
  mutate(inctot = case_when(
    inctot == 999999999 ~ NA_real_,
    TRUE ~ as.numeric(inctot)
  )) %>%
  mutate(incwelfr = case_when(
    incwelfr == 999999 ~ NA_real_,
    TRUE ~ incwelfr
  )) %>%
  mutate(incunemp = case_when(
    incunemp == 999999 ~ NA_real_,
    TRUE ~ as.numeric(incunemp)
  )) %>%
  mutate(ctccrd = case_when(
    ctccrd == 999999 ~ NA_real_,
    TRUE ~ as.numeric(ctccrd)
  )) %>%
  mutate(eitcred = case_when(
    eitcred == 9999 ~ NA_real_,
    TRUE ~ as.numeric(eitcred)
  )) %>%
  mutate(immigrant = case_when(
    citizen == 1 ~ 1,
    citizen >= 2 & citizen <= 5 ~ 0,
    TRUE ~ NA_real_
  )) %>%
    mutate(wksunem1 = case_when(
    wksunem1 == 99 ~ 0,
    TRUE ~ as.numeric(wksunem1)
  )) %>%
    mutate(wksunem2 = case_when(
    wksunem2 == 9 ~ 0,
    TRUE ~ as.numeric(wksunem2)
  )) %>%
  select(-starts_with("q"), -asecwt, -month, -asecflag, -statecensus, -asecwth, -pernum, -cpsidp) # Drop quality flags and variables we don't need
  # NOTE: the 'immigrant' variable is 1 for people born in the U.S.; 0 for people born in the U.S. outlying territories (PR, Guam), people born abroad of American parents, naturalized citizens, and non-citizens; and NA for people marked as NIU.

asec_allyears <- as_survey_design(cps_svy, weights = asecwtcvd)

asec2019 <- asec_allyears %>%
  filter(year == 2019)

asec2020 <- asec_allyears %>%
  filter(year == 2020)

asec2021 <- asec_allyears %>%
  filter(year == 2021)

asec_allyears_imm <- asec_allyears %>%
  filter(immigrant == 1)

asec2019_imm <- asec2019 %>%
  filter(immigrant == 1)

asec2020_imm <- asec2020 %>%
  filter(immigrant == 1)

asec2021_imm <- asec2021 %>%
  filter(immigrant == 1)
  
```

```{r EDA}
# % unemployed, employed, out of labor force in each 
asec_allyears %>%
  drop_na(employed) %>%
  select(year, employed) %>%
  group_by(year, employed) %>%
  summarise(pct = survey_prop()*100) %>%
  ggplot(aes(x=year, y=pct, fill=factor(employed))) + 
  geom_col(position="dodge") +
  labs(
    title = "Percentage of Unemployed and Employed Out of the Labor Force",
    subtitle = "(in % for 2019, 2020, 2021)",
    caption = "Source: IPUMS Data",
    x = "Year",
    y = "%",
    fill = "Status",
  ) +
  geom_text(aes(label = round(pct,2)), 
                position = position_dodge(width = 1), 
                color="black",vjust = -.2) +
  scale_fill_hue(labels = c("Unemployed", "Employed")) +
  theme(legend.title = element_blank()) +
  theme_minimal()
 

# How does employment vary by age?
# employed
asec_allyears %>%
   mutate(
    # Create categories
    age_group = case_when(
      age > 17 & age <= 25 ~ "18-24",
      age > 24 & age <= 31 ~ "25-31",
      age > 21 & age <= 38 ~ "32-38",
      age > 38 & age <= 45 ~ "39-45",
      age > 45 & age <= 52 ~ "46-52",
      age > 52 & age <= 59 ~ "53-59",
      age > 59 & age <= 65 ~ "60-65"
    )) %>%
  drop_na(employed) %>%
  filter(employed == 1) %>%
  select(year, employed, age, age_group) %>%
  group_by(year, age_group) %>%
  summarise(cnt = n()) %>%
  mutate(freq = percent(cnt / sum(cnt))) %>%
  ggplot(aes(x=age_group, y=freq, fill=factor(year))) + 
  geom_col(position="dodge") +
  geom_text(aes(age_group, label = freq), position = position_dodge(width = 1), hjust = -.25) +
  coord_flip() +
  scale_y_continuous(labels = scales::percent, limits = c(0,.3)) +
  labs(
    title = "Employed by Age Group",
    subtitle = "(for 2019, 2020, 2021)",
    caption = "Source: IPUMS Data",
    x = "Age Group",
    y = "",
    fill = "Year",
  ) +
  theme(legend.title = element_blank()) +
  theme_minimal()

# unemployed
asec_allyears %>%
   mutate(
    # Create categories (18-24; 24-30; 31-37; 38-44, 45-51, 52-58, 58-64)
    age_group = case_when(
      age > 17 & age <= 25 ~ "18-24",
      age > 24 & age <= 31 ~ "25-31",
      age > 21 & age <= 38 ~ "32-38",
      age > 38 & age <= 45 ~ "39-45",
      age > 45 & age <= 52 ~ "46-52",
      age > 52 & age <= 59 ~ "53-59",
      age > 59 & age <= 65 ~ "60-65"
    )) %>%
  drop_na(employed) %>%
  filter(employed == 0) %>%
  select(year, employed, age, age_group) %>%
  group_by(year, age_group) %>%
  summarise(cnt = n()) %>%
  mutate(freq = percent(cnt / sum(cnt))) %>%
  ggplot(aes(x=age_group, y=freq, fill=factor(year))) + 
  geom_col(position="dodge") +
  geom_text(aes(age_group, label = freq), position = position_dodge(width = 1), hjust = -.25) +
  coord_flip() +
  scale_y_continuous(labels = scales::percent, limits = c(0,.35)) +
  labs(
    title = "Unemployed by Age Group",
    subtitle = "(in % for 2019, 2020, 2021)",
    caption = "Source: IPUMS Data",
    x = "Age Group",
    y = "",
    fill = "Status",
  ) +
  theme(legend.title = element_blank()) +
  theme_minimal()

# put this two graphs side by side


# this is trying to put unemployed and employed together but I cant find the way to also divide by year
# asec_allyears %>%
#    mutate(
#     # Create categories
#     age_group = case_when(
#       age <= 14            ~ "0-14",
#       age > 14 & age <= 24 ~ "15-24",
#       age > 24 & age <= 34 ~ "25-34",
#       age > 34 & age <= 44 ~ "35-44",
#       age > 44 & age <= 54 ~ "45-54",
#       age > 54 & age <= 64 ~ "55-64",
#       age > 64 & age <= 74 ~ "65-74",
#       age > 74 ~ "75+"
#     )) %>%
#   drop_na(employed) %>%
#   filter(empstat != 30) %>%
#   select(year, employed, age, age_group) %>%
#   group_by(year, employed, age_group) %>%
#   summarise(cnt = n()) %>%
#   mutate(freq = percent(cnt / sum(cnt))) %>%
#   ggplot(aes(x=age_group, y=freq, fill=factor(employed))) + 
#   geom_col(position="dodge") +
#   coord_flip() +
#   scale_y_continuous(labels = scales::percent) +
#   labs(
#     title = "Percentage of Unemployed and Employed Out of the Labor Force",
#     subtitle = "(in % for 2019, 2020, 2021)",
#     caption = "Source: IPUMS Data",
#     x = "Age Group",
#     y = "",
#     fill = "Status",
#   ) +
#   scale_fill_hue(labels = c("Unemployed", "Employed")) +
#   theme(legend.title = element_blank()) +
#   theme_minimal()

# dumbbell % unemployed by state between 2019 and 2020
status_bystate <- asec_allyears %>%
  drop_na(employed) %>%
  filter(year ==2019 | year == 2020) %>%
  select(year, employed, statefip) %>%
  group_by(year, statefip, employed) %>% 
  summarise(cnt = n()) %>%
  mutate(freq = percent(cnt / sum(cnt))) 

status_bystate %>%
  filter(employed == 0) %>%
  select(year, statefip, freq) %>%
  pivot_wider(names_from = year, values_from = freq) %>%
  ggplot(aes(x=`2019`, xend=`2020`, y=as_label(statefip))) +
  geom_dumbbell(color="#a3c4dc", 
                colour_x="#edae52", 
                      colour_xend = "#9fb059",
                      size=0.75, 
                      point.colour.l="#0e668b") + 
  scale_x_continuous(label = percent)  +
  labs(
    title = "Unemployed by State",
    subtitle = "(2019 'yellow' and 2020 'green')",
    caption = "Source: IPUMS Data",
    x = "",
    y = "States",
  ) +
  theme_minimal()

# percentage change of unemployed people 
a <- asec_allyears %>%
  drop_na(employed) %>%
  select(year, employed) %>%
  group_by(year, employed) %>%
  summarise(cnt = n()) %>%
  filter(employed == 0)

# PIERINA: CAN YOU FIX THIS SO THAT IT LOOKS LIKE THE VERSION THAT WORKS? I COULDN'T FIGURE OUT
# HOW TO REPLICATE....
a %>%
  mutate(pct_change = round((a$cnt/lag(a$cnt) - 1) * 100, 2))
  # why I get NA if round((a$cnt/lag(a$cnt) - 1) * 100, 2) works. being a the table before mutate

```

